---
title: "1.3 Lägesmått"
output: 
  revealjs::revealjs_presentation:
    css: style1.css
    self_contained: false
    transition: fade
    reveal_options:
      width: "80%"
      height: "80%"
      minScale: 1
      maxScale: 1
      controls: false
      progress: false
editor_options: 
  chunk_output_type: console
---

# 

<h2>Lägesmått</h2>

<h4>Medelvärde, median, mode</h4>

##

Illustration

##

Vektornotation

$$\mathbf x = (x_1, x_2, ..., x_n)$$

Exempel

$$\mathbf x = (12,43,12)$$

#

<h2>Medelvärde</h2>

(Det aritmetiska medelvärdet)

##

<div class="formula">
$$\bar x = \frac{summa}{antal} = \frac{\sum\limits_{\tiny{i = 1}}^{\tiny{n}} x_i}{n}$$
</div>

##

Exempel och illustration

##

Extremvärden

##

**R**

```{r}
dat <- c(112, 145, 131)
mean(dat)
```

#

<h2>Median</h2>

##

**Medianen** är ett värde sådant att 

(1) minst hälften av observationerna är mindre än medianen, och 

(2) minst hälften av observationerna är större än medianen

<br>

Om observationerna ordnas från minsta till största värde, är medianen i mitten av serien

##

Udda antal värden

Illustration

## 

Jämt antal värden

Illustration

##

Medianens ordningstal

<div class="formula">
$$\frac{n + 1}{2}$$
</div>

#

<h2>Mode (typvärde)</h2>

##

**Mode** är det vanligaste värdet i datamängden

Illustration

##

Behöver ej ha ett unikt mode

Illustration

##

Främst användbart om få utfall

Illustration

##

Tillämpligt oavsett datatyp

#

<h2>Val av lägesmått</h2>

##

Symmetrisk fördelning med unik topp

##

Sneda fördelningar

##

Kopplingar till variabeltyper

##

<div style="height:750px;width:100%;background:#000;border-radius:30px;">
</div>